# This file was generated by GoReleaser. DO NOT EDIT.
class OneBuild < Formula
  desc "Frictionless way of managing project-specific commands"
  homepage "https://github.com/gopinath-langote/1build"
  version "1.4.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gopinath-langote/1build/releases/download/v1.4.3/1build_1.4.3_Darwin_x86_64.tar.gz"
    sha256 "28be4a624a761ab5189202b604a9d13a63c5a7c83cf7271f1912478666fc694f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gopinath-langote/1build/releases/download/v1.4.3/1build_1.4.3_Linux_x86_64.tar.gz"
      sha256 "e85567500a4c6c9fcec17daa731d64eb77477626fb18090feaa1f75c9fbb5a3c"
    end
  end

  def install
    bin.install "1build"
  end

  test do
    system "#{bin}/1build --version"
  end
end
