# This file was generated by GoReleaser. DO NOT EDIT.
class OneBuild < Formula
  desc "Frictionless way of managing project-specific commands"
  homepage "https://github.com/gopinath-langote/1build"
  version "1.4.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gopinath-langote/1build/releases/download/v1.4.3/1build_1.4.3_Darwin_x86_64.tar.gz"
    sha256 "fe8ab89737af8f7f833e638e6779d3c57ebc246ec037fa46511412011e9c25c2"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gopinath-langote/1build/releases/download/v1.4.3/1build_1.4.3_Linux_x86_64.tar.gz"
      sha256 "54ddcc5ad3131e4b32f7423f0a05385eb38df11df08325c41de90793d4629173"
    end
  end

  def install
    bin.install "1build"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end

  test do
    system "#{bin}/1build --version"
  end
end
