# This file was generated by GoReleaser. DO NOT EDIT.
class OneBuild < Formula
  desc "Frictionless way of managing project-specific commands"
  homepage "https://github.com/gopinath-langote/1build"
  version "1.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gopinath-langote/1build/releases/download/v1.4.0/1build_1.4.0_Darwin_x86_64.tar.gz"
    sha256 "cab310a296bd4e24ab44f7f550a5e4747b4bd60b53e481fc16b164e45a66c5bd"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gopinath-langote/1build/releases/download/v1.4.0/1build_1.4.0_Linux_x86_64.tar.gz"
      sha256 "2169464eb0bcdd0ddf7455fc2390ff7c69709af1ca5d06296e57d8439f87dc84"
    end
  end

  def install
    bin.install "1build"
  end

  test do
    system "#{bin}/1build --version"
  end
end
